services:
  - type: web
    name: cashflow-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cashflow-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: XERO_CLIENT_ID
        sync: false
      - key: XERO_CLIENT_SECRET
        sync: false
      - key: XERO_REDIRECT_URI
        value: https://cashflow-backend.onrender.com/auth/xero/callback

databases:
  - name: cashflow-db
    databaseName: cashflow
    user: cashflow_user
